### ISSUE TITLE
Change digital signature algorithms to use SHA256

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/keyczar#17]
```
Change as per NIST recommendations
```

Original issue reported on code.google.com by `stevew...@gmail.com` on 12 Aug 2008 at 5:46

**Comment by wsargent** [comment]
Putting together some references to track this bug...

Discussion: 
- https://groups.google.com/forum/#!msg/keyczar-discuss/B2EVtVRU4DU/hCqlAsT8eTUJ
- https://groups.google.com/forum/#!searchin/keyczar-discuss/SHA-1/keyczar-discuss/nbnz2Oj-9e4/K6roOZ2bgLAJ

[SHA-1 prestart collision attack](https://sites.google.com/site/itstheshappening/) and [Arstechnica](http://arstechnica.com/security/2012/10/sha1-crypto-algorithm-could-fall-by-2018/) link:

> "Now, based on research completed last month, the international team of researchers believe that such an attack could be carried out this year for $75,000 to $120,000. The much lower cost is the result of efficiencies the researchers discovered in the way graphics cards can use a technique known as "boomeranging" to find SHA1 collisions."

[SP 800-131A](http://csrc.nist.gov/publications/nistpubs/800-131A/sp800-131A.pdf) "SHA-1 shall not be used for digital signature generation after December 31, 2013"

**Comment by jbtule** [comment]
This one is very sad that it has sat so long, while the pull request wasn't complete, it was pretty close, see comments:
https://code.google.com/r/pschorf-keyczar/source/detail?r=06a78002feb632cd75ff423b15958eec9fcd60ef

For reference, a functioning keytype in C# fixed for this issue ( added in the unofficial namespace since since it doesn't exist in other keyczars).
https://github.com/jbtule/keyczar-dotnet/blob/master/Keyczar/Keyczar/Unofficial/RsaPrivateSignKey.cs
https://github.com/jbtule/keyczar-dotnet/blob/master/Keyczar/Keyczar/Unofficial/RsaPublicSignKey.cs

**Comment by wsargent** [comment]
@jbtule From the pull request it looks like stylistic changes at best.  How come it didn't make it?

**Comment by jbtule** [comment]
@wsargent A bit more than stylistic, they were things that needed adjusted security wise, like for the digest algorithm being chosen, and for interoperability such as the key representation in json file and how the key material should be hashed to identify it. However, you are right in that these things were pretty trivial and identified in the review, and were (and still are) easy to fix.
